import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0F172A' },
  header: {
    paddingTop: 60,
    paddingHorizontal: 25,
    paddingBottom: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  greeting: { color: '#94A3B8', fontSize: 16 },
  userName: { color: '#FFF', fontSize: 24, fontWeight: 'bold' },
  profileBadge: { padding: 8 },
  content: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 20,
    paddingTop: 30,
  },
  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: '#1E293B', marginBottom: 20 },
  
  filterContainer: { 
    marginBottom: 20, 
  },
  
  filterScroll: { 
    paddingLeft: 2, 
    alignItems: 'center',
    paddingVertical: 7,
  },
  
  filterTab: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#FFF',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    minHeight: 42,
  },
  filterTabActive: { backgroundColor: '#3B82F6', borderColor: '#3B82F6' },
  filterText: { color: '#64748B', fontWeight: '600', fontSize: 14 },
  filterTextActive: { color: '#FFF' },
  cardWrapper: { marginBottom: 15 },
  ticketCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
      android: { elevation: 3 },
    }),
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  statusDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
  statusBadgeText: { fontSize: 11, fontWeight: 'bold' },
  dateText: { color: '#94A3B8', fontSize: 12 },
  ticketTitle: { fontSize: 17, fontWeight: 'bold', color: '#1E293B', marginBottom: 6 },
  ticketDescription: { fontSize: 14, color: '#64748B', lineHeight: 20, marginBottom: 15 },
  ticketImage: {
    width: '100%',
    height: 160,
    borderRadius: 12,
    marginTop: 12,
    marginBottom: 4,
    backgroundColor: '#E2E8F0',
  },
  ticketImagePlaceholder: {
    width: '100%',
    height: 160,
    borderRadius: 12,
    marginTop: 12,
    marginBottom: 4,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ticketImagePlaceholderText: {
    marginTop: 8,
    color: '#64748B',
    fontSize: 13,
  },
  cardFooter: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#F1F5F9', paddingTop: 12 },
  tag: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F1F5F9', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, marginRight: 8 },
  tagText: { color: '#64748B', fontSize: 11, fontWeight: '600', marginLeft: 4 },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    backgroundColor: '#3B82F6',
    width: 65,
    height: 65,
    borderRadius: 32.5,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
});